name: mainstream-taste-bias
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - altair==5.0.1
  - hydra-core=1.3.2
  - numba=0.57.0
  - numpy==1.24.3
  - pandas=1.5.3
  - pip=23.2.1
  - pyarrow=11.0.0
  - scikit-learn=1.0.2
  - scipy=1.10.1
  - pip:
    - inequalipy==1.0.5
