defaults:
  - _self_
  - data: faces
  - model: ease

random_state: 0

# Metric used to evaluate best parameters
val_metric: fcp
val_metric_minimize: False

# Cross validation parameters
test_folds:
  _target_: sklearn.model_selection.StratifiedKFold
  n_splits: 5
  shuffle: True
  random_state: ${random_state}

val_fold:
  _target_: sklearn.model_selection.train_test_split
  train_size: 0.75
  random_state: ${random_state}

hydra:
  job:
    chdir: True
  output_subdir: .
  run:
    dir: outputs/
  sweep:
    dir: outputs/
    subdir: ${hydra.job.override_dirname}
